VirtoCommerce/vc-module-search

src/VirtoCommerce.SearchModule.Core/ModuleConstants.cs, src/VirtoCommerce.SearchModule.Core/VirtoCommerce.SearchModule.Core.csproj, src/VirtoCommerce.SearchModule.Data/BackgroundJobs/BackgroundJobsRunner.cs, src/VirtoCommerce.SearchModule.Data/Handlers/ObjectSettingEntryChangedEventHandler.cs, src/VirtoCommerce.SearchModule.Data/VirtoCommerce.SearchModule.Data.csproj, src/VirtoCommerce.SearchModule.Web/Localizations/en.VirtoCommerce.Search.json, src/VirtoCommerce.SearchModule.Web/Module.cs, src/VirtoCommerce.SearchModule.Web/VirtoCommerce.SearchModule.Web.csproj
https://virtocommerce.atlassian.net/browse/VP-2348
=> Refactor to apply setting values immediately #VP-2348

src/VirtoCommerce.SearchModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VP-3123
=> VP-3123: Fix logo

src/VirtoCommerce.SearchModule.Web/Scripts/widgets/index-widget.tpl.html
VP-6364 Add icons to widgets inside Product blade
Add icon to the widget
=> VP-6364: Add icons to widgets inside Product blade

src/VirtoCommerce.SearchModule.Web/Scripts/blades/index-detail.js, src/VirtoCommerce.SearchModule.Web/Scripts/blades/index-progress.js
=> VP-6864: Fix header icon

src/VirtoCommerce.SearchModule.Core/ModuleConstants.cs, src/VirtoCommerce.SearchModule.Core/VirtoCommerce.SearchModule.Core.csproj, src/VirtoCommerce.SearchModule.Data/VirtoCommerce.SearchModule.Data.csproj, src/VirtoCommerce.SearchModule.Web/VirtoCommerce.SearchModule.Web.csproj
[Validation on settings input fields](https://virtocommerce.atlassian.net/browse/VP-6756)
User can enter negative digits in input fields where values should be positive 
Update platform dependency
Use suitable value type for input validation
=> VP-6756: Fix validation on settings input fields

src/VirtoCommerce.SearchModule.Web/Module.cs, src/VirtoCommerce.SearchModule.Web/package-lock.json
https://virtocommerce.atlassian.net/browse/PT-867
=> PT-868: Enable own indexing progress notifications for each request

src/VirtoCommerce.SearchModule.Data/BackgroundJobs/IndexingJobs.cs, src/VirtoCommerce.SearchModule.Data/BackgroundJobs/JobCancellationTokenWrapper.cs, src/VirtoCommerce.SearchModule.Data/VirtoCommerce.SearchModule.Data.csproj, src/VirtoCommerce.SearchModule.Web/VirtoCommerce.SearchModule.Web.csproj, src/VirtoCommerce.SearchModule.Web/module.manifest
Reverts VirtoCommerce/vc-module-search#43
=> Revert "PT-777: Remove redundant class and update dependencies"

src/VirtoCommerce.SearchModule.Web/Content/css/common.css, src/VirtoCommerce.SearchModule.Web/Scripts/blades/index-progress.js, src/VirtoCommerce.SearchModule.Web/Scripts/blades/index-progress.tpl.html
https://virtocommerce.atlassian.net/browse/PT-1929
=> PT-1931 Add progress bar to indexation blade

src/VirtoCommerce.SearchModule.Core/Extenstions/DynamicPropertyTypeExtensions.cs
=> PT-2563 Added extensions to convert dynamic property type to indexed type

README.md, src/VirtoCommerce.SearchModule.Core/ModuleConstants.cs, src/VirtoCommerce.SearchModule.Web/Localizations/en.VirtoCommerce.Search.json, src/VirtoCommerce.SearchModule.Web/Scripts/search-index.js
=> PT-5710: Add Search Index menu access permission

.github/workflows/main.yml, .github/workflows/publish_nugets.yml, Directory.Build.props, src/VirtoCommerce.SearchModule.Core/VirtoCommerce.SearchModule.Core.csproj, src/VirtoCommerce.SearchModule.Data/VirtoCommerce.SearchModule.Data.csproj, src/VirtoCommerce.SearchModule.Web/VirtoCommerce.SearchModule.Web.csproj, src/VirtoCommerce.SearchModule.Web/module.manifest, tests/VirtoCommerce.SearchModule.Tests/VirtoCommerce.SearchModule.Tests.csproj
Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956
=> PT-1956: Bump .Net and EF up to 6

Directory.Build.props, src/VirtoCommerce.SearchModule.Core/Model/IndexState.cs, src/VirtoCommerce.SearchModule.Core/Model/SearchRequest.cs, src/VirtoCommerce.SearchModule.Core/Services/IIndexingManager.cs, src/VirtoCommerce.SearchModule.Core/Services/ISearchProvider.cs, src/VirtoCommerce.SearchModule.Data/Services/BatchIndexingOptions.cs, src/VirtoCommerce.SearchModule.Data/Services/DummySearchProvider.cs, src/VirtoCommerce.SearchModule.Data/Services/IndexingManager.cs, src/VirtoCommerce.SearchModule.Web/Controllers/SearchIndexationModuleController.cs, src/VirtoCommerce.SearchModule.Web/Localizations/en.VirtoCommerce.Search.json, src/VirtoCommerce.SearchModule.Web/Scripts/blades/indexes-list.js, src/VirtoCommerce.SearchModule.Web/Scripts/blades/indexes-list.tpl.html, src/VirtoCommerce.SearchModule.Web/Scripts/resources/search-index.js, src/VirtoCommerce.SearchModule.Web/module.manifest, tests/VirtoCommerce.SearchModule.Tests/SearchProvider.cs
https://virtocommerce.atlassian.net/browse/PT-6520
=> PT-6520: Add Blue Green indexation support

src/VirtoCommerce.SearchModule.Web/Localizations/en.VirtoCommerce.Search.json
Fixed localization file by correcting mistakes and rewrote some sentences.
https://virtocommerce.atlassian.net/browse/PT-5016
=> docs: Fix localization file

Directory.Build.props, src/VirtoCommerce.SearchModule.Core/Model/IndexDocumentChangeType.cs, src/VirtoCommerce.SearchModule.Core/Model/IndexingParameters.cs, src/VirtoCommerce.SearchModule.Core/Services/ISearchProvider.cs, src/VirtoCommerce.SearchModule.Core/Services/ISupportIndexSwap.cs, src/VirtoCommerce.SearchModule.Core/Services/ISupportPartialUpdate.cs, src/VirtoCommerce.SearchModule.Data/BackgroundJobs/IndexingJobs.cs, src/VirtoCommerce.SearchModule.Data/Services/DummySearchProvider.cs, src/VirtoCommerce.SearchModule.Data/Services/Extensions.cs, src/VirtoCommerce.SearchModule.Data/Services/IndexingManager.cs, src/VirtoCommerce.SearchModule.Web/Controllers/SearchIndexationModuleController.cs, src/VirtoCommerce.SearchModule.Web/module.manifest, tests/VirtoCommerce.SearchModule.Tests/SearchProvider.cs, tests/VirtoCommerce.SearchModule.Tests/SearchProviderTests.cs
Known issues:
* If the search provider supports partial indexation, creating a new product is not triggering indexation
* Changing variation is not triggering main product reindexation
https://virtocommerce.atlassian.net/browse/PT-6878
=> PT-6878: Revert breaking changes of ISearchProvider

src/VirtoCommerce.SearchModule.Data/BackgroundJobs/IndexingJobs.cs, src/VirtoCommerce.SearchModule.Data/Services/IndexingManager.cs, tests/VirtoCommerce.SearchModule.Tests/IndexingJobTests.cs
https://virtocommerce.atlassian.net/browse/PT-6646
=> PT-6646: Variations fixes

src/VirtoCommerce.SearchModule.Web/Scripts/blades/indexes-list.js, src/VirtoCommerce.SearchModule.Web/Scripts/blades/indexes-list.tpl.html
Hide swap menu for N/A slot
https://virtocommerce.atlassian.net/browse/PT-6960
=> PT-6960: Hide swap menu for N/A slot

src/VirtoCommerce.SearchModule.Data/BackgroundJobs/IndexingJobs.cs
Disable concurrent execution for IndexChangesJob
https://virtocommerce.atlassian.net/browse/PT-7789
=> PT-7789: Disable concurrent execution for IndexChangesJob

src/VirtoCommerce.SearchModule.Core/VirtoCommerce.SearchModule.Core.csproj, src/VirtoCommerce.SearchModule.Data/BackgroundJobs/BackgroundJobsRunner.cs, src/VirtoCommerce.SearchModule.Data/BackgroundJobs/IndexProgressHandler.cs, src/VirtoCommerce.SearchModule.Data/BackgroundJobs/IndexingJobs.cs
Add indexation progress-bar, messages, errors to the job detail:
https://virtocommerce.atlassian.net/browse/PT-8031
=> PT-8031: Add indexation log to the Hangfire job history

src/VirtoCommerce.SearchModule.Web/Scripts/blades/indexes-list.tpl.html, src/VirtoCommerce.SearchModule.Web/Scripts/dialogs/reindex-dialog.tpl.html
Fix name of permission 'search:index:rebuild' to build index
https://virtocommerce.atlassian.net/browse/PT-8193
=> PT-8193: Fix name of permission to build index

src/VirtoCommerce.SearchModule.Data/BackgroundJobs/IndexingJobs.cs
Multithreading logic is removed
https://virtocommerce.atlassian.net/browse/PT-8036
=> PT-8036: Multithreading logic is removed

README.md, VirtoCommerce.SearchModule.sln, src/VirtoCommerce.SearchModule.Core/Model/GeoPoint.cs, src/VirtoCommerce.SearchModule.Web/module.manifest, tests/VirtoCommerce.SearchModule.Tests/GeoPointTests.cs
fix: Virto GeoPoint supports 10 digits after decimal. 
https://virtocommerce.atlassian.net/browse/PT-6602
=> PT-6602: Virto GeoPoint supports 10 digits after decimal

src/VirtoCommerce.SearchModule.Web/Localizations/ru.VirtoCommerce.Search.json
=> Updated ru localization

src/VirtoCommerce.SearchModule.Data/BackgroundJobs/IndexProgressHandler.cs
https://virtocommerce.atlassian.net/browse/PT-9532
=> PT-9532: Fix problem with progress bar value, add warning

src/VirtoCommerce.SearchModule.Web/package-lock.json, src/VirtoCommerce.SearchModule.Web/package.json, src/VirtoCommerce.SearchModule.Web/webpack.config.js
feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395
=> PT-9395: add nodejs-lts support

src/VirtoCommerce.SearchModule.Core/Model/IndexDocumentField.cs, src/VirtoCommerce.SearchModule.Web/module.manifest
fix: Merge for field IsCollection only
https://virtocommerce.atlassian.net/browse/PT-11722
=> PT-11722: Merge for field IsCollection only

src/VirtoCommerce.SearchModule.Core/Model/SuggestionRequest.cs, src/VirtoCommerce.SearchModule.Core/Model/SuggestionResponse.cs, src/VirtoCommerce.SearchModule.Core/Services/ISupportSuggestions.cs, src/VirtoCommerce.SearchModule.Data/Services/DummySearchProvider.cs, tests/VirtoCommerce.SearchModule.Tests/SearchProviderTests.cs
https://virtocommerce.atlassian.net/browse/PT-11848
=> PT-11848: Add suggestions

src/VirtoCommerce.SearchModule.Core/Extenstions/IndexDocumentExtensions.cs, src/VirtoCommerce.SearchModule.Core/Model/IndexDocumentField.cs, src/VirtoCommerce.SearchModule.Core/Model/SuggestionRequest.cs
https://virtocommerce.atlassian.net/browse/PT-1180
=> PT-1180: add IsSuggestable field to IndexDocumentField and  additional params to suggestion request

src/VirtoCommerce.SearchModule.Core/Extensions/IndexDocumentDynamicPropertyExtensions.cs
https://virtocommerce.atlassian.net/browse/PT-13040
=> PT-13040: Add extension methods for dynamic properties indexing

src/VirtoCommerce.SearchModule.Core/Extensions/ConfigurationExtensions.cs
https://virtocommerce.atlassian.net/browse/PT-14556
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Search_3.404.0-pr-99-5b67.zip
=> PT-14556: Add SearchProviderActive() extension method

src/VirtoCommerce.SearchModule.Core/ModuleConstants.cs, src/VirtoCommerce.SearchModule.Data/Services/IndexingManager.cs, src/VirtoCommerce.SearchModule.Web/Localizations/en.VirtoCommerce.Search.json, tests/VirtoCommerce.SearchModule.Tests/IndexingManagerTests.cs
Disabled by default
https://virtocommerce.atlassian.net/browse/PT-13953
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Search_3.406.0-pr-101-4879.zip
=> PT-13953: add enable partial update setting

src/VirtoCommerce.SearchModule.Data/Services/IndexingManager.cs
https://virtocommerce.atlassian.net/browse/VCST-691
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Search_3.802.0-pr-105-d15e.zip
=> VCST-691: start index when documents exist only

src/VirtoCommerce.SearchModule.Core/Extensions/SearchDocumentExtensions.cs, src/VirtoCommerce.SearchModule.Core/Model/IHasRelevanceScore.cs, src/VirtoCommerce.SearchModule.Core/ModuleConstants.cs
https://virtocommerce.atlassian.net/browse/VCST-1454
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Search_3.803.0-pr-107-c664.zip
=> VCST-1454: add IHasRelevanceScore interface

src/VirtoCommerce.SearchModule.Core/ModuleConstants.cs, src/VirtoCommerce.SearchModule.Web/Controllers/Api/SearchIndexationModuleController.cs
https://virtocommerce.atlassian.net/browse/VCST-2969
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Search_3.810.0-pr-115-9cb9.zip
=> VCST-2969: Add missing permission checks
